apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: safari
  name: safari
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safari
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: safari
    spec:
      containers:
        - image: httpd:2.4.41-alpine
          name: httpd
          resources: {}
          volumeMounts:
            - mountPath: "/tmp/safari-data"
              name: myvol
      volumes:
        - name: myvol
          persistentVolumeClaim:
            claimName: safari-pvc
status: {}

