apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx3
  name: nginx3
spec:
  containers:
  - image: nginx
    name: nginx3
    resources: {}
    volumeMounts:
    - name: nfsvol
      mountPath: /tmp/nfs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: nfsvol
    persistentVolumeClaim:
      claimName: pvc-nfs
status: {}
