apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - sh
            - -c
            - echo $JOB_COMPLETION_INDEX >> /tmp/job_pv/output
            image: busybox
            name: job
            resources: {}
            volumeMounts:
              - name: pv
                mountPath: /tmp/job_pv
          restartPolicy: Never
          volumes:
            - name: "pv"
              hostPath:
                path: /tmp/job_pv
status: {}
