apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  completions: 5
  parallelism: 3
  completionMode: Indexed
  template:
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo $JOB_COMPLETION_INDEX >> /tmp/job_pv/output
        image: busybox
        name: job
        resources: {}
        volumeMounts:
          - name: pv
            mountPath: /tmp/job_pv
      restartPolicy: Never
      volumes:
        - name: "pv"
          hostPath:
            path: /tmp/job_pv
status: {}
