apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container-playground
  name: multi-container-playground
spec:
  containers:
  - image: nginx:1.17.6-alpine
    name: c1
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    resources: {}
    volumeMounts:
      - mountPath: /your/vol/path/
        name: volume
  - image: busybox:1.31.1
    name: c2
    args:
      - sh
      - -c
      - "while true; do date >> /your/vol/path/date.log; sleep 1; done"
    resources: {}
    volumeMounts:
      - mountPath: /your/vol/path/
        name: volume
  - image: busybox:1.31.1
    name: c3
    args:
      - sh
      - -c
      - "tail -f /your/vol/path/date.log"
    resources: {}
    volumeMounts:
      - mountPath: /your/vol/path/
        name: volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: volume
      emptyDir: {}
status: {}
